# Generated by Django 5.1.1 on 2024-10-28 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_event_eventbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('response_data', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventbooking')),
            ],
        ),
    ]
