# Generated by Django 5.1.1 on 2024-10-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_amount',
            new_name='price',
        ),
    ]
