# Generated by Django 5.1.1 on 2024-10-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_rename_booking_amount_booking_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
