# Generated by Django 5.1.1 on 2024-10-28 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_gallery_payment_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype'),
        ),
    ]
