# Generated by Django 5.1.1 on 2024-11-01 05:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_gallery_options_alter_roomimage_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
