# Generated by Django 5.1.1 on 2024-11-01 05:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_roomtype_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
