# Generated by Django 5.1.1 on 2024-11-05 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_alter_roomtype_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='room_price', to='rooms.roomtype'),
        ),
    ]
