# Generated by Django 5.1.1 on 2024-11-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_alter_roombooking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='price_per_night',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
