# Generated by Django 5.1.1 on 2024-10-28 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_banners_career_controlpanel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Career',
            new_name='Careers',
        ),
    ]
