# Generated by Django 5.1.1 on 2024-10-29 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_career_careers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banners',
            table='banners',
        ),
    ]
