# Generated by Django 5.1.1 on 2024-11-01 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_banners_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='careers',
            options={'verbose_name_plural': 'Careers'},
        ),
    ]
